version: '3'
services:
  nextjs-seller:
    build: .
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_BASE_URL_AUTH=http://your-api.com
      # add more env vars as needed