
export const brandAnalysisData = [
  {
    id: "INV001",
    name: "Ketchup",
    category: 'Drinks',
    revenue: "2800",
    monthOnMonthVolumeGrowth: "20%",
    noOfCustomers: '10',
    noOfInvoices: "10",
    reOrder: 'medium',
  },
  {
    id: "INV002",
    name: "Ketchup",
    category: 'Drinks',
    revenue: "2800",
    monthOnMonthVolumeGrowth: "20%",
    noOfCustomers: '10',
    noOfInvoices: "10",
    reOrder: 'medium',
  },
  {
    id: "INV003",
    name: "Ketchup",
    category: 'Drinks',
    revenue: "2800",
    monthOnMonthVolumeGrowth: "20%",
    noOfCustomers: '10',
    noOfInvoices: "10",
    reOrder: 'medium',
  },
  {
    id: "INV004",
    name: "Ketchup",
    category: 'Drinks',
    revenue: "2800",
    monthOnMonthVolumeGrowth: "20%",
    noOfCustomers: '10',
    noOfInvoices: "10",
    reOrder: 'medium',
  },
  {
    id: "INV005",
    name: "Ketchup",
    category: 'Drinks',
    revenue: "2800",
    monthOnMonthVolumeGrowth: "20%",
    noOfCustomers: '10',
    noOfInvoices: "10",
    reOrder: 'medium',
  },
  {
    id: "INV006",
    name: "Ketchup",
    category: 'Drinks',
    revenue: "2800",
    monthOnMonthVolumeGrowth: "20%",
    noOfCustomers: '10',
    noOfInvoices: "10",
    reOrder: 'medium',
  },
  {
    id: "INV007",
    name: "Ketchup",
    category: 'Drinks',
    revenue: "2800",
    monthOnMonthVolumeGrowth: "20%",
    noOfCustomers: '10',
    noOfInvoices: "10",
    reOrder: 'medium',
  },
  {
    id: "INV008",
    name: "Ketchup",
    category: 'Drinks',
    revenue: "2800",
    monthOnMonthVolumeGrowth: "20%",
    noOfCustomers: '10',
    noOfInvoices: "10",
    reOrder: 'medium',
  },
  {
    id: "INV009",
    name: "Ketchup",
    category: 'Drinks',
    revenue: "2800",
    monthOnMonthVolumeGrowth: "20%",
    noOfCustomers: '10',
    noOfInvoices: "10",
    reOrder: 'medium',
  },
  {
    id: "INV0010",
    name: "Ketchup",
    category: 'Drinks',
    revenue: "2800",
    monthOnMonthVolumeGrowth: "20%",
    noOfCustomers: '10',
    noOfInvoices: "10",
    reOrder: 'medium',
  }
]
