
export const invoiceData = [
  {
    id: "INV001",
    name: "Tomato Ketchup",
    mrp: '5',
    brand: "Heinz",
    store: "demo",
    closingStock: '10',
    avgWeeklySale: "120",
    itemSpeed: '50',
  },
  {
    id: "INV002",
    name: "Toor Dal",
    mrp: '5',
    brand: "Heinz",
    store: "demo",
    closingStock: '10',
    avgWeeklySale: "120",
    itemSpeed: '50',
  },
  {
    id: "INV003",
    name: "Chilli Powder",
    mrp: '5',
    brand: "Heinz",
    store: "demo",
    closingStock: '10',
    avgWeeklySale: "120",
    itemSpeed: '50',
  },
  {
    id: "INV001",
    name: "Tomato Ketchup",
    mrp: '5',
    brand: "Heinz",
    store: "demo",
    closingStock: '10',
    avgWeeklySale: "120",
    itemSpeed: '50',
  },
  {
    id: "INV002",
    name: "Toor Dal",
    mrp: '5',
    brand: "Heinz",
    store: "demo",
    closingStock: '10',
    avgWeeklySale: "120",
    itemSpeed: '50',
  },
  {
    id: "INV003",
    name: "Chilli Powder",
    mrp: '5',
    brand: "Heinz",
    store: "demo",
    closingStock: '10',
    avgWeeklySale: "120",
    itemSpeed: '50',
  },
  {
    id: "INV001",
    name: "Tomato Ketchup",
    mrp: '5',
    brand: "Heinz",
    store: "demo",
    closingStock: '10',
    avgWeeklySale: "120",
    itemSpeed: '50',
  },
  {
    id: "INV002",
    name: "Toor Dal",
    mrp: '5',
    brand: "Heinz",
    store: "demo",
    closingStock: '10',
    avgWeeklySale: "120",
    itemSpeed: '50',
  },
  {
    id: "INV003",
    name: "Chilli Powder",
    mrp: '5',
    brand: "Heinz",
    store: "demo",
    closingStock: '10',
    avgWeeklySale: "120",
    itemSpeed: '50',
  },
  {
    id: "INV001",
    name: "Tomato Ketchup",
    mrp: '5',
    brand: "Heinz",
    store: "demo",
    closingStock: '10',
    avgWeeklySale: "120",
    itemSpeed: '50',
  },
  {
    id: "INV002",
    name: "Toor Dal",
    mrp: '5',
    brand: "Heinz",
    store: "demo",
    closingStock: '10',
    avgWeeklySale: "120",
    itemSpeed: '50',
  },
  {
    id: "INV003",
    name: "Chilli Powder",
    mrp: '5',
    brand: "Heinz",
    store: "demo",
    closingStock: '10',
    avgWeeklySale: "120",
    itemSpeed: '50',
  },
  {
    id: "INV001",
    name: "Tomato Ketchup",
    mrp: '5',
    brand: "Heinz",
    store: "demo",
    closingStock: '10',
    avgWeeklySale: "120",
    itemSpeed: '50',
  },
  {
    id: "INV002",
    name: "Toor Dal",
    mrp: '5',
    brand: "Heinz",
    store: "demo",
    closingStock: '10',
    avgWeeklySale: "120",
    itemSpeed: '50',
  },
  {
    id: "INV003",
    name: "Chilli Powder",
    mrp: '5',
    brand: "Heinz",
    store: "demo",
    closingStock: '10',
    avgWeeklySale: "120",
    itemSpeed: '50',
  },
  {
    id: "INV001",
    name: "Tomato Ketchup",
    mrp: '5',
    brand: "Heinz",
    store: "demo",
    closingStock: '10',
    avgWeeklySale: "120",
    itemSpeed: '50',
  },
  {
    id: "INV002",
    name: "Toor Dal",
    mrp: '5',
    brand: "Heinz",
    store: "demo",
    closingStock: '10',
    avgWeeklySale: "120",
    itemSpeed: '50',
  },
  {
    id: "INV003",
    name: "Chilli Powder",
    mrp: '5',
    brand: "Heinz",
    store: "demo",
    closingStock: '10',
    avgWeeklySale: "120",
    itemSpeed: '50',
  }
]
