
export const invoiceAnalysisData = [
    {
        id: "INV001",
        category: 'Drinks',
        averageOrderValue: '6',
        monthOnMonthVolumeGrowth: "20%",
        noOfCustomers: '10',
        noOfInvoices: "10",
        totalRevenue: "2800",
    },
    {
        id: "INV002",
        category: 'Drinks',
        averageOrderValue: '6',
        monthOnMonthVolumeGrowth: "20%",
        noOfCustomers: '10',
        noOfInvoices: "10",
        totalRevenue: "2800",
    },
    {
        id: "INV003",
        category: 'Drinks',
        averageOrderValue: '6',
        monthOnMonthVolumeGrowth: "20%",
        noOfCustomers: '10',
        noOfInvoices: "10",
        totalRevenue: "2800",
    },
    {
        id: "INV004",
        category: 'Drinks',
        averageOrderValue: '6',
        monthOnMonthVolumeGrowth: "20%",
        noOfCustomers: '10',
        noOfInvoices: "10",
        totalRevenue: "2800",
    },
    {
        id: "INV005",
        category: 'Drinks',
        averageOrderValue: '6',
        monthOnMonthVolumeGrowth: "20%",
        noOfCustomers: '10',
        noOfInvoices: "10",
        totalRevenue: "2800",
    },
    {
        id: "INV006",
        category: 'Drinks',
        averageOrderValue: '6',
        monthOnMonthVolumeGrowth: "20%",
        noOfCustomers: '10',
        noOfInvoices: "10",
        totalRevenue: "2800",
    },
    {
        id: "INV007",
        category: 'Drinks',
        averageOrderValue: '6',
        monthOnMonthVolumeGrowth: "20%",
        noOfCustomers: '10',
        noOfInvoices: "10",
        totalRevenue: "2800",
    },
    {
        id: "INV008",
        category: 'Drinks',
        averageOrderValue: '6',
        monthOnMonthVolumeGrowth: "20%",
        noOfCustomers: '10',
        noOfInvoices: "10",
        totalRevenue: "2800",
    },
    {
        id: "INV009",
        category: 'Drinks',
        averageOrderValue: '6',
        monthOnMonthVolumeGrowth: "20%",
        noOfCustomers: '10',
        noOfInvoices: "10",
        totalRevenue: "2800",
    },
    {
        id: "INV0010",
        category: 'Drinks',
        averageOrderValue: '6',
        monthOnMonthVolumeGrowth: "20%",
        noOfCustomers: '10',
        noOfInvoices: "10",
        totalRevenue: "2800",
    },
]